# Generated by Django 6.0 on 2025-12-15 00:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Alimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('calorias', models.FloatField()),
                ('proteinas', models.FloatField(help_text='Gramas de proteína')),
                ('carboidratos', models.FloatField(help_text='Gramas de carboidrato')),
                ('gorduras', models.FloatField(help_text='Gramas de gordura')),
                ('data_consumo', models.DateField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
