# Generated by Django 6.0 on 2025-12-15 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alimento',
            name='carboidratos',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='alimento',
            name='gorduras',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='alimento',
            name='proteinas',
            field=models.FloatField(default=0),
        ),
    ]
